# Generated by Django 4.1.1 on 2022-11-03 10:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_applicant', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО заявителя')),
                ('gender', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='Ж', max_length=2)),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('health_status', models.TextField(blank=True, default='Практически здоров', help_text='Аллергоамамнез, хронические заболевания и т.п.', verbose_name='Состояние здоровья')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Заявители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название службы')),
                ('code', models.CharField(max_length=100, verbose_name='Код службы')),
                ('number', models.CharField(max_length=100, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Экстренная служба',
                'verbose_name_plural': 'Экстренные службы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_appeal', models.CharField(choices=[('WR', 'Мужчина'), ('FN', 'Женщина')], default='WR', max_length=2)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата обращения')),
                ('number', models.UUIDField(default=uuid.uuid4, verbose_name='Номер обращения')),
                ('number_cases', models.IntegerField(default=1, verbose_name='Количество пострадавших')),
                ('not_call', models.BooleanField(default=False, verbose_name='Не звонить')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='emergency_service.applicant', verbose_name='Заявитель')),
                ('service', models.ManyToManyField(related_name='appeals', to='emergency_service.emergencyservice', verbose_name='Экстренная служба')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['date', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['number'], name='appeal_number_idx'),
        ),
    ]
