# Generated by Django 4.1.1 on 2022-11-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО заявителя')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('health_status', models.TextField(verbose_name='Состояние здоровья')),
                ('number', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Заявители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название службы')),
                ('code', models.IntegerField(verbose_name='Код службы')),
                ('number', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Экстренная служба',
                'verbose_name_plural': 'Экстренные службы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата обращения')),
                ('number', models.IntegerField(verbose_name='Номер обращения')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_service.applicant', verbose_name='Заявитель')),
                ('service', models.ManyToManyField(to='emergency_service.emergencyservice', verbose_name='Экстренная служба')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['date', 'number'],
            },
        ),
    ]
