# Generated by Django 4.1.1 on 2022-11-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='emergency_service.applicant', verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='service',
            field=models.ManyToManyField(related_name='services', to='emergency_service.emergencyservice', verbose_name='Экстренная служба'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='emergencyservice',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код службы'),
        ),
    ]
