# Generated by Django 4.1.1 on 2022-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='name_father',
            field=models.CharField(default=1, max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='surname',
            field=models.CharField(default=1, max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status_appeal',
            field=models.CharField(choices=[('WR', 'В работе'), ('FN', 'Завершено')], default='WR', max_length=2, verbose_name='Статус обращения'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='Ж', max_length=2, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo_applicant',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото заявителя'),
        ),
    ]
