# Generated by Django 4.1.1 on 2022-11-07 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service', '0002_applicant_name_father_applicant_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Номер обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status_appeal',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Завершено', 'Завершено')], default='В работе', max_length=10, verbose_name='Статус обращения'),
        ),
    ]
