# Generated by Django 4.1.1 on 2022-11-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service', '0002_alter_appeal_applicant_alter_appeal_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='Ж', max_length=2),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='emergency_service.applicant', verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='service',
            field=models.ManyToManyField(related_name='appeals', to='emergency_service.emergencyservice', verbose_name='Экстренная служба'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='health_status',
            field=models.TextField(blank=True, verbose_name='Состояние здоровья'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер телефона'),
        ),
    ]
