# Generated by Django 4.1.1 on 2022-11-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service', '0003_alter_appeal_number_alter_appeal_status_appeal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['date'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterField(
            model_name='appeal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
    ]
