# Generated by Django 4.1.1 on 2022-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service', '0005_alter_appeal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appeal',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, related_name='appeals', to='emergency_service.emergencyservice', verbose_name='Экстренная служба'),
        ),
    ]
