# Generated by Django 4.1.1 on 2022-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service', '0006_appeal_slug_applicant_slug_alter_appeal_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='appeals', to='emergency_service.emergencyservice', verbose_name='Экстренная служба'),
        ),
    ]
