# Generated by Django 4.1.1 on 2022-11-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service', '0007_alter_appeal_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='slug',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
