# Generated by Django 4.1.1 on 2022-11-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service', '0008_remove_applicant_slug_alter_appeal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
